### PR TITLE
Improve light source graphic

### PR DESCRIPTION
**Pull request by JLBegin**
- Added method `Solid.orient(Vector)` to orient solid towards a direction Vector (useful for source graphic). A great complement to the existing method `Solid.rotate(xTheta, yTheta, zTheta)` for euler rotations.
- Display directional light sources as a 3D arrow toward source direction.
- Add optional `source` argument in `Scene.show()` to show the light source during a scene preview.
- Add argument `displaySize` to Sources. 

Example from `ex01.py`:
image

### CODE REVIEW

**Comment by PyMarc2** [comment]
Everything works on my end after commit [17a53f8](https://github.com/DCC-Lab/PyTissueOptics/pull/97/commits/17a53f8803307450ed8b61dda91a0e7a22462a5c).

**Review by PyMarc2 — APPROVED** [review]

**Comment by PyMarc2** [comment]
The `between` method from the Vector class is not working properly.
One should include more tests. The case Vector(1,1,1) `between` Vector(-1,-1,-1) is not working.
A proper method should be provided regardless of its "meaninlessness" in the package.

```
    def testBetweenOppositePlanesOrientations_shouldReturnExpectedRotation(self):
        fromOrientation = Vector(1, 1, 1)
        toOrientation = Vector(-1, -1, -1)
        expectedRotation = Rotation(180, 0, -90)

        rotation = Rotation.between(fromOrientation, toOrientation)

        self.assertEqual(expectedRotation.xTheta, rotation.xTheta)
        self.assertEqual(expectedRotation.yTheta, rotation.yTheta)
        self.assertEqual(expectedRotation.zTheta, rotation.zTheta)
```

**Comment by JLBegin** [comment]
I will tackle this soon. Currently the only important case to thoroughly test first is to get the proper euler rotation matrix to orient the original source graphics direction vector (0, 0, 1) to any output vector. I would not mind limiting it to this single input vector if the general case is too complex.

**Comment by JLBegin** [comment]
Changed orient() method to simply use the Vector.rotateAround mechanic (axis-angle).

**Pull request merged**
